### ISSUE TITLE
Possible to get Asp Net Core 3.0 version of this feature

### ISSUE THREAD

**Issue by shantrendz** [primaryobjects/MVC-Creep-Collector#2]
Hi,
Have gone through xml based data annotation in MVC 4 version. Since Microsoft recently released Asp Core 3.0, some of the libraries are taken out. 
Can you please suggest some inputs to handle the same feature in Asp Core 3.0 ?

**Comment by primaryobjects** [comment]
Please feel free to fork with this feature. Thank you. :)

**Comment by shantrendz** [comment]
Great!! Have already started exploring it.. Will keep you posted.
